config/routes.rb
Rails.application.routes.draw do
  
  root to: 'videos#index'
  
  get    'home'    => 'static_pages#home'
  get    'leagues' => 'static_pages#leagues'
  get    'help'    => 'static_pages#help'
  get    'newvideos'    => 'videos#new'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  get    'forgot_password'  => 'sessions#new'
  get    'signup'  => 'sessions#new'
  
  get 'forgot password' => 'password_resets#new'
  get 'edit password' => 'password_resets#edit'
  
  get 'sign', to: 'sessions#from_omniauth'
  get 'auth/failure', to: redirect('/')
 
  post   'login'   => 'sessions#create'

  delete 'logout'  => 'sessions#destroy'
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :videos,              only: [:index, :new, :create, :destroy]
  resources :video_uploads,       only: [:new, :create]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <!--<small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>-->
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  <div class="container-fluid">
    <%= link_to "pegasus", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-left">
      <li><button type="button" class="btn btn-default navbar-btn"><%= link_to 'Add video now!', new_video_path %></button></li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', home_path %></li>
        <li><%= link_to 'Videos', root_path %></li>
        <li><%# link_to 'Add Video', new_video_path %></li>
        <li><%= link_to 'Leagues', leagues_path %></li>
        <li><%# link_to 'Help', help_path %></li>
      
      <% if logged_in? %>
        <li><%= link_to 'Users', users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li><%= link_to "Log out", logout_path, method: "delete" %></li>
          </ul>
        </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
        
        <li><button type="button" class="btn btn-default navbar-btn"><%= link_to "Sign up now!", signup_path %></button></li>
        
        <% if current_user %>
        <li>
          <span class="navbar-text" .pull-right><%= current_user.name %></span>
        </li>
        <li><%# link_to 'Log Out', logout_path, method: "delete" %></li>
        <% else %>
        <li><%# link_to 'Sign In', '/auth/google_oauth2' %></li>
        <% end %>
      
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= yield(:title) %> | Pegasus</title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    


<!--test
  <div class="container">
    <%# flash.each do |key, value| %>
      <div class="alert alert-<%# key %>">
        <%# value %>
      </div>
    <%# end %>
  </div>   
-->    
    
    
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>